# Site settings
encoding: UTF-8
title: Gare
repository: TankedThomas/gare.works
description: "Welcome to Gare"
domain: tankedthomas.github.io
url: https://www.gare.works # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username: TankedThomas

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-spaceship

# Theme settings
logo: "/assets/images/logo.png"
site-logo: "/assets/images/logo.svg"
logo_path: "/assets/images/logo.svg"

# Page settings
page_excerpts: true
# paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - "*.code-workspace"
  - "*.gemspec"
  - "/vendor/"
  - "contact-form"
  - "Gemfile.lock"
  - "Gemfile"
  - "LICENSE.md"
  - "node_modules"
  - "Rakefile"
  - "README.md"
